# -*- coding: utf-8 -*-
"""pickleoctree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WM4X4AfaEzcEx2R5pS5eUmuWOBzJetTY
"""

import pickle
def saveOctree(octree,inputName):
  with open(inputName,"wb") as file:
    pickle.dump(octree,file)

def readOctree(inputName):
  with open(inputName,"rb") as file:
    data=pickle.load(file)
  return data

def check():
    print("yes")
